# U-Net Training Configuration

# Model settings
model:
  type: "unet"
  variant: "standard"
  n_channels: 3
  n_classes: 3
  bilinear: false
  base_channels: 64

# Training settings
training:
  batch_size: 16
  num_epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0001
  optimizer: "adam"
  scheduler: "cosine"
  warmup_epochs: 5

# Loss function
loss:
  type: "combined"
  l1_weight: 0.8
  perceptual_weight: 0.2
  ssim_weight: 0.1

# Data settings
data:
  train_low_dir: "data/processed/LOL/train/low"
  train_normal_dir: "data/processed/LOL/train/high"
  val_low_dir: "data/processed/LOL/test/low"
  val_normal_dir: "data/processed/LOL/test/high"
  image_size: [256, 256]
  num_workers: 4
  augmentation: true
  paired: true

# Hardware settings
hardware:
  device: "auto"  # auto, cpu, cuda, mps
  mixed_precision: true
  compile_model: false

# Checkpointing
checkpoint:
  save_dir: "models/checkpoints"
  save_every: 10
  keep_last: 5
  monitor_metric: "val_psnr"
  mode: "max"

# Logging
logging:
  use_wandb: false
  project_name: "low-light-enhancement"
  log_every: 100
  log_images: true
  num_log_images: 4

# Evaluation
evaluation:
  metrics: ["psnr", "ssim", "lpips"]
  save_examples: true
  num_examples: 10

# Early stopping
early_stopping:
  patience: 15
  min_delta: 0.001
  restore_best_weights: true
